# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=regionhalland&apiToken=%PACKAGIST_APIKEY%' -d'{"repository":{"url":"https://regionhalland.visualstudio.com/public.RhWebStyleguide/_git/RhWebStyleguide"}}'
  displayName: 'Skickar nytt paket till till Packagist.org'
